config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: "maps#top"
  get "maps/index", to: "maps#index",as: "index"

  resources :battles, only: [:show]
  get '/attack', to: 'battles#attack', as: 'attack'

  resources :monsters, only: [:index,:show]
  get "/get", to: "monsters#get"
  patch "/get/:id", to: "monsters#getUpdateBattle", as: 'getupbattle'
  patch "/get/:id/in", to: "monsters#getUpdateIn", as: 'getupin'
  patch "/update/:id", to: "monsters#update"
  get "/redirect", to: "maps#redirect"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/map.rb
class Map < ApplicationRecord
end

app/models/monster.rb
class Monster < ApplicationRecord
  has_many :monster_users
  has_many :users, through: :monster_users
  
end

app/models/monster_user.rb
class MonsterUser < ApplicationRecord
  belongs_to :user
  belongs_to :monster
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :monster_users       
  has_many :monsters, through: :monster_users
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/battles_controller.rb
class BattlesController < ApplicationController
  def show
    @page = params[:id]
    @monster = Monster.where(field: @page)
    @enemy = @monster.order("RAND()").first
    @my_monster = Monster.find(current_user.current_monster_id)
    
  end

  def attack
    @enemy = Monster.find(11)
  end
end

app/controllers/maps_controller.rb
class MapsController < ApplicationController

  def top

  end
    
  def index
    
    @current_user_monster = Monster.find_by(id:current_user.current_monster_id)
    if @current_user_monster == nil
      MonsterUser.create(user_id:current_user.id,monster_id:1)
      User.update(current_monster_id:1)
    end
    @current_user_monster = Monster.find_by(id:current_user.current_monster_id)
    binding.pry
  end

  def redirect
    @monster = Monster.find(1)
    @user = User.find(1)
    redirect_to root_path
  end  
end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController
  def index
    @user = User.find(current_user.id)
    @monsters = @user.monsters
  end


  def get
    @enemy = Monster.order("RAND()").first
  end

  def show
    @monster = Monster.find(params[:id])
  end
  
  def update
    @user = User.find(current_user.id)
    @user.update(current_monster_id: params[:id])
    redirect_to index_path
  end

  def get
    @enemy = Monster.where( 'id >= ?', rand(Monster.first.id..Monster.last.id) ).first
  end

  def getUpdateBattle
    @user = User.find(current_user.id)
    @enemy = Monster.find(params[:id])
    @user.update(current_monster_id: @enemy.id)
    @monster_user = MonsterUser.new(user_id: current_user.id,monster_id:@enemy.id)
    @monster_user.save
    redirect_to index_path
  end

  def getUpdateIn
    @user = User.find(current_user.id)
    @enemy = Monster.find(params[:id])
    @monster_user = MonsterUser.new(user_id: current_user.id,monster_id:@enemy.id)
    @monster_user.save
    redirect_to index_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/battles_helper.rb
module BattlesHelper
end

app/helpers/maps_helper.rb
module MapsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/battles/show.html.haml
.battle-wrapper
  .enemy
    .enemy__name
      = "#{@enemy.name} が あらわれた"
    .enemy__hp
      = "HP : #{@enemy.hp}"
  = image_tag @enemy.image, class: "enemy-img"

  .player
    .player__command
      = "#{@my_monster.name} は どうする？"
      %p{id: "battle"} 
        = icon 'fas', 'caret-right' 
        せんとう
      %p{id: "escape"} 
        にげる

    .player__command2
      = "#{@my_monster.name} は どうする？"
      %p{id: "attack"}
        こうげき
      %p{id: "deffens"}
        ぼうぎょ
      %p{id: "back"}
        もどる

    .player__attack
      .give-attack
        = "#{@my_monster.name} の こうげき!!"
      .give-attack-count#playerAttack
        = "#{@enemy.name} に #{@my_monster.attack} の こうげき を あたえた"

    .enemy__attack
      .eat-attack
        = "#{@enemy.name} の こうげき!!"
      .eat-attack-count#enemyAttack
        = "#{@my_monster.name} は #{@enemy.attack} の ダメージ を くらった"



    -# .player__border
    .player__status
      %p{class: "player__status--name"}
        ="#{@my_monster.name}"
      %p{class: "player__status--hp"} 
        ="HP : #{@my_monster.hp}" 

//--------------------------------- Enemy -------------------------------------------//
%input{name: "enemy_name", type: "hidden", value: @enemy.name, id: 'enemy_name' }
%input{name: "enemy_hp", type: "hidden", value: @enemy.hp, id: 'enemy_hp' }
%input{name: "enemy_attack", type: "hidden", value: @enemy.attack, id: 'enemy_attack' }

//--------------------------------- Player -------------------------------------------//
%input{name: "my_monster_name", type: "hidden", value: @my_monster.name, id: 'my_monster_name' }
%input{name: "my_monster_hp", type: "hidden", value: @my_monster.hp, id: 'my_monster_hp' }

%input{name: "my_monster_attack", type: "hidden", value: @my_monster.attack, id: 'my_monster_attack' }



= audio_tag "/assets/audios/battle.mp3", controls: false, autoplay: true, loop: true
= audio_tag "/assets/audios/punch.mp3", controls: false, preload: true, id: "punch"
= audio_tag "/assets/audios/monster.mp3", controls: false, preload: true, id: "cry"

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title PocketQuest
    = csrf_meta_tags
    = csp_meta_tag
    %script{:src => "https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"}
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

    = icon 'fas', 'volume-up'
    = icon 'fas', 'volume-mute'
    = audio_tag "/assets/audios/cursor.mp3", controls: false, preload: true, id: "cursor"

app/views/maps/index.html.haml
.side-bar
  
  .current_monster
    ="戦闘用モンスター : #{@current_user_monster.name}"
    %img{src:@current_user_monster.image}
    .henkou
      = "変更 : Pキー"
  .email
    ="ユーザー名 : #{current_user.email}"  
  .log_out
    = link_to "ログアウト", destroy_user_session_path, method: :delete 
.wrapper
  .clear
  #0.icon
    
    %img{src:"/move/右向き.gif",class:"right"}
    %img{src:"/move/主人公.gif",class:"bottom"}
    %img{src:"/move/左向き.gif",class:"left"}
    %img{src:"/move/後ろ向き.gif",class:"top active"}
    %img{src:"/move/ラプラス左.gif",class:"rapu_left"}
    %img{src:"/move/ラプラス右.gif",class:"rapu_right"}
    %img{src:"/move/ラプラス上.gif",class:"rapu_top"}
    %img{src:"/move/ラプラス下.gif",class:"rapu_bottom"}
  .men
    %img{src:"/trainer/男トレーナー.png"}
  .women
    %img{src:"/trainer/女トレーナー.png"}
  .ooo
    %img{src:"/trainer/オーキド.png"}
  .green
    %img{src:"/trainer/グリーン右.png"}  
  .silver
    %img{src:"/trainer/シルバー右.png"} 
  .gara
    %img{src:"/monster/ギャラドス.gif"}
  .rwomen
    %img{src:"/trainer/ロケット団女.png"}
  .rmen    
    %img{src:"/trainer/ロケット団男.png"}
  .adult
    %img{src:"/trainer/大人のお姉さん.png"}

%input{type:"hidden",class:"id",value:@id}
%input{type:"hidden",class:"top_move",value:@top}
%input{type:"hidden",class:"left_move",value:@left}

= audio_tag "/assets/audios/top.mp3", controls: false, loop: true, autoplay: true

app/views/maps/top.html.haml
.top-wrapper
  ポケットクエスト
  .top-title
    はじめる：Enterキー

app/views/monsters/get.html.haml
.get-wrapper
  #monster-name
    = @enemy.name
    %br
    %span げっとだぜ！
  #monster
    = image_tag @enemy.image
  #get-button 
    #get-button__center
    #get-button__point

.modal-coin
  %p
    モンスター を げっと しよう
  #pay-ok
    げっとする

.modal-get
  %p
    = "#{@enemy.name} を げっとした!"
  
  = link_to "戦闘で使う", getupbattle_path(@enemy.id), class: "back-btn", method: :patch
  = link_to "手持ちに加える", getupin_path(@enemy.id), class: "back-btn", method: :patch

.overlay


= audio_tag "/assets/audios/gacha.mp3", controls: false, loop: true, autoplay: true, id: "gacha"
= audio_tag "/assets/audios/get.mp3", controls: false, loop: false, autoplay: false, id: "get"

app/views/monsters/index.html.haml
.index-wrapper
  .your-monster
    あなたの所持モンスター
  .monsters-index
    - @monsters.each do |monster|
      .monster-index
        = link_to monster_path(monster) do
          = monster.name
          %img{src:monster.image}
  .monster-no-select
    = "戻る : Tキー"

app/views/monsters/show.html.haml
.monsters-show-wrapper
  .monster-show-name
    = @monster.name
  .monster-show
    .monster-image
      %img{src:@monster.image}
    .monster-status  
      HP
      = @monster.hp
      攻撃力    
      = @monster.attack
  .monster-select
    = link_to "戦闘で使う","/update/#{@monster.id}",method: :patch
  .monster-no-select
    = link_to "戻る","/monsters"